{"trial_id": "01", "hyperparameters": {"space": [{"class_name": "Choice", "config": {"name": "activation_type", "default": "relu", "conditions": [], "values": ["relu", "leaky_relu"], "ordered": false}}, {"class_name": "Int", "config": {"name": "num_layers", "default": null, "conditions": [], "min_value": 2, "max_value": 4, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_layer_0", "default": null, "conditions": [], "min_value": 15, "max_value": 25, "step": 5, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_layer_1", "default": null, "conditions": [], "min_value": 15, "max_value": 25, "step": 5, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "learning_rate", "default": 0.01, "conditions": [], "values": [0.01, 0.001, 0.0001], "ordered": true}}, {"class_name": "Choice", "config": {"name": "batch_size", "default": 5000, "conditions": [], "values": [5000, 10000, 15000], "ordered": true}}, {"class_name": "Int", "config": {"name": "units_layer_2", "default": null, "conditions": [], "min_value": 15, "max_value": 25, "step": 5, "sampling": "linear"}}], "values": {"activation_type": "relu", "num_layers": 3, "units_layer_0": 15, "units_layer_1": 20, "learning_rate": 0.01, "batch_size": 15000, "units_layer_2": 15}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/home/diego/Documents/10. Machine Learning/1. ETH/6. ClassProjects/Insurance_Prediction/.venv/lib/python3.12/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/home/diego/Documents/10. Machine Learning/1. ETH/6. ClassProjects/Insurance_Prediction/.venv/lib/python3.12/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/diego/Documents/10. Machine Learning/1. ETH/6. ClassProjects/Insurance_Prediction/.venv/lib/python3.12/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/diego/Documents/10. Machine Learning/1. ETH/6. ClassProjects/Insurance_Prediction/.venv/lib/python3.12/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/tmp/ipykernel_1056692/1625549285.py\", line 41, in fit\n    return model.fit(\n           ^^^^^^^^^^\n  File \"/home/diego/Documents/10. Machine Learning/1. ETH/6. ClassProjects/Insurance_Prediction/.venv/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/home/diego/Documents/10. Machine Learning/1. ETH/6. ClassProjects/Insurance_Prediction/.venv/lib/python3.12/site-packages/keras/src/metrics/__init__.py\", line 211, in get\n    raise ValueError(f\"Could not interpret metric identifier: {identifier}\")\nValueError: Could not interpret metric identifier: val_loss\n"}